version: '3.8'

services:
  mysql_test:
    image: mysql:8.0
    restart: always

    environment:
      MYSQL_DATABASE: test_cars_02
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - "3307"
    networks:
      - cars-02-network
    volumes:
      - "./persistence/src/test/data/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./persistence/src/test/data/data.sql:/docker-entrypoint-initdb.d/2.sql"

  mysql_main:
    image: mysql:8.0
    restart: always

    environment:
      MYSQL_DATABASE: cars_02
      MYSQL_ROOT_PASSWORD: main
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    networks:
      - cars-02-network
    volumes:
      - "mysql_cars_02:/var/lib/mysql"
      - "./api/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  cars_02_web_app:
    image: pietrasfilip/cars-02-app:1.0
    ports:
      - "8080:8080"
    restart: always
    networks:
      - cars-02-network
    depends_on:
      mysql_main:
        condition: service_healthy

volumes:
  mysql_test:
  mysql_cars_02:
  cars_02_web_app:
networks:
  cars-02-network: